name: Upload Artifacts to S3
on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to S3
        uses: Noelware/s3-action@2
        with:
          directories: |
            ./build
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          endpoint: s3.amazonaws.com
          prefix: /artifacts
          region: us-east-1
          bucket: my-artifactee-bucket
